### ISSUE TITLE
freefilesync package doesn't work as expected

### ISSUE THREAD

**Issue by instinctualjealousy** [bogdaba/scoop-bucket#1]
## Bug Report
**Package Name:** freefilesync

### Current Behaviour
This doesn't get around FreeFileSync's draconian install.dat check, which means the main program is unusable

### Expected Behaviour
For it to succeed launch, but I should've known better

### Possible Solution
Binary patching FFS to remove install.dat check- but making a script that could successfully do this on every build sounds daunting, illegal, and of questionable moral character, and I don't want to stoop as low as the FFS author here

**Comment by bogdaba** [comment]
Sorry for the trouble.
Looks like incompatibility with scoop and etc. is by design (https://github.com/ScoopInstaller/Extras/issues/3750)

**Comment by successtheman** [comment]
I know I am a bit late here, but there is source code available for freefilesync available here https://freefilesync.org/download/FreeFileSync_12.4_Source.zip, is this source only for specific parts of the program? or is there anything else preventing someone from forking freefilesync?
